apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbclient-deployment
  labels:
    app: mongodb-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-demo
      type: client
  template:
    metadata:
      labels:
        app: mongodb-demo
        type: client
    spec:
      containers:
      - name: mongoclient-container
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database-url
